# Generated by Django 5.1.7 on 2025-03-16 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_ad_name_advertisement_ad_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
